services:
  dnscheck:
    build: .
    image: dnscheck:latest
    container_name: dnscheck
    restart: unless-stopped
    env_file: .env
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web

networks:
  web:
    external: true
